# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91dd7780d459cd01b69b8caae206745bf0db8ee3084f687d34a6dfc15c4fab7fcaef2a176cd7c7c56064fdb3f4a366f50e554e0b29c22dcd35eed4a02df93596

test:
  secret_key_base: e43399e6852a6dec58423f56909c40fe010a513b9b4c5ec89f5e88bd84aa3f5df0b051149479178b1d20df1ab1c7737f90709e0389f733adb65d719d84dd8ad7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
